[build]
  base = "fe"
  command = "npm run build"
  publish = "fe/build"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"

# Redirect all requests to index.html for React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Environment variables for production
[context.production.environment]
  REACT_APP_API_URL = "https://stock-management-system-1-p6xu.onrender.com"
  REACT_APP_ENV = "production"

# Environment variables for branch deploys
[context.branch-deploy.environment]
  REACT_APP_API_URL = "https://stock-management-system-1-p6xu.onrender.com"
  REACT_APP_ENV = "staging"